sudo: false
language: node_js

notifications:
  email:
    on_success: never
    on_failure: change

script: 
  - npm install $TYPESCRIPT --force 

env:
  - TYPESCRIPT=typescript@2.0
  - TYPESCRIPT=typescript@latest
  - TYPESCRIPT=typescript@next

node_js:
  - "stable"
