sudo: false
os:
  - osx
  - linux

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi
  - npm install -g npm@latest
  - npm install -g typescript
  - npm install -g typings
  - npm install -g bower
  - npm install -g gulp

install:
  - npm install
  - typings install
  - bower install
  
before_script: 
  - gulp build
